# SPDX-License-Identifier: MIT
"""Mesh conversion and file export (STL / OBJ)."""

from __future__ import annotations

from typing import List, Tuple
import warnings

import numpy as np

from models.facet import Facet


def facets_to_mesh(facets: List[Facet]) -> Tuple[np.ndarray, np.ndarray]:
    """
    Convert list of Facet to (vertices, triangle_faces).

    When a facet carries a denser point grid (samples_u/v > 2),
    the grid is triangulated; otherwise the classic 4-corner quad
    is split into two triangles.
    """
    vertices: List[List[float]] = []
    faces: List[List[int]] = []
    offset = 0

    for f in facets:
        pts = f.mesh_points()
        nu = getattr(f, "samples_u", 2)
        nv = getattr(f, "samples_v", 2)

        # Guard: if points length does not match expected grid, fall back
        if pts.shape[0] != nu * nv:
            warnings.warn(
                f"facet ({f.index_u},{f.index_v}) 采样点数 {pts.shape[0]} 与 "
                f"{nu}x{nv} 网格不符，已退化为 4 角两三角形导出",
                stacklevel=2,
            )
            nu, nv = 2, 2
            pts = f.corners

        vertices.extend(pts.tolist())

        # Triangulate the regular grid
        for j in range(nv - 1):
            for i in range(nu - 1):
                i00 = offset + j * nu + i
                i10 = offset + j * nu + (i + 1)
                i01 = offset + (j + 1) * nu + i
                i11 = offset + (j + 1) * nu + (i + 1)
                # Two triangles, consistent winding
                faces.append([i00, i10, i11])
                faces.append([i00, i11, i01])

        offset += pts.shape[0]

    return np.asarray(vertices, dtype=float), np.asarray(faces, dtype=int)


def export_stl(vertices: np.ndarray, faces: np.ndarray, path: str) -> None:
    """Write ASCII STL."""
    with open(path, "w", encoding="utf-8") as fp:
        fp.write("solid MF_Reflector\n")
        for tri in faces:
            v0 = vertices[tri[0]]
            v1 = vertices[tri[1]]
            v2 = vertices[tri[2]]
            n = np.cross(v1 - v0, v2 - v0)
            ln = np.linalg.norm(n)
            if ln > 1e-12:
                n = n / ln
            else:
                n = np.array([0.0, 0.0, 1.0])
            fp.write(f"  facet normal {n[0]:.6e} {n[1]:.6e} {n[2]:.6e}\n")
            fp.write("    outer loop\n")
            for idx in tri:
                v = vertices[idx]
                fp.write(f"      vertex {v[0]:.6e} {v[1]:.6e} {v[2]:.6e}\n")
            fp.write("    endloop\n")
            fp.write("  endfacet\n")
        fp.write("endsolid MF_Reflector\n")


def export_obj(vertices: np.ndarray, faces: np.ndarray, path: str) -> None:
    """Write Wavefront OBJ."""
    with open(path, "w", encoding="utf-8") as fp:
        fp.write("# MacroFocal Reflector generated by mf_reflector\n")
        for v in vertices:
            fp.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
        for tri in faces:
            # OBJ is 1-based
            fp.write(f"f {tri[0]+1} {tri[1]+1} {tri[2]+1}\n")
