# SPDX-License-Identifier: MIT
"""
MFReflector aggregate – the main design object.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import List

from .source import PointSource
from .grid import GridLayout
from .gaps import GapsConfig
from .spreads import SpreadsConfig
from .facet import Facet
from .enums import PatchContinuity, PatchFitMethod, SolveMethod


@dataclass
class MFReflector:
    """
    MacroFocal Reflector design object.

    Geometry is generated by geometry.engine.generate_facets() using:
      - carrier paraboloid (grid.focal)
      - reflection-law normals from source + spreads
      - relative slope integration (solve order)
    """
    name: str = "MF_Reflector"
    source: PointSource = field(default_factory=PointSource.default)
    grid: GridLayout = field(default_factory=GridLayout)
    gaps: GapsConfig = field(default_factory=GapsConfig)
    spreads: SpreadsConfig = field(default_factory=SpreadsConfig)
    # 未参与几何求解（几何形状与反射率无关）；能量仿真不在本项目范围。TODO: 若做能量核算需接入
    reflection_coefficient: float = 1.0

    # Integration order (params.py: solve)
    solve: SolveMethod = SolveMethod.V_FIRST

    # Mesh density per facet
    mesh_u: int = 5
    mesh_v: int = 5

    # Solver / F.Start controls
    solver_iterations: int = 5
    solver_tolerance: float = 1e-5
    calculation_start_u: float | None = None
    calculation_start_v: float | None = None
    reference_position_u: float = 0.0
    reference_position_v: float = 0.0
    # False (default): connect to the neighbour rigidly at the reference
    # position — the facet keeps its exact optical design (spread = set range).
    # True: force the full shared-edge curve to match the neighbour; edges are
    # watertight (C0) but each facet's optics are bent near that border.
    use_base_curve_from_neighbor: bool = False
    z_step_u: float = 0.0
    z_step_v: float = 0.0

    # Solve patch parameter
    patch_fit_method: PatchFitMethod = PatchFitMethod.APPROXIMATE
    fit_patches_u: int = 1
    fit_patches_v: int = 1
    fit_patch_continuity_u: PatchContinuity = PatchContinuity.POINT
    fit_patch_continuity_v: PatchContinuity = PatchContinuity.POINT

    # Generated result
    facets: List[Facet] = field(default_factory=list, repr=False)

    def is_generated(self) -> bool:
        return len(self.facets) > 0

    def clear_geometry(self) -> None:
        self.facets.clear()

    def summary(self) -> str:
        g = self.grid
        lines = [
            f"MFReflector '{self.name}'",
            f"  Source   : {self.source}",
            f"  Grid     : {g.grid_type.value}  {g.n_u}×{g.n_v}  "
            f"size=({g.total_width:.1f}×{g.total_height:.1f}) mm  focal={g.focal:.1f}",
            f"  Gaps     : enabled={self.gaps.enabled}  "
            f"type={self.gaps.gap_type.value}  "
            f"size_u/v=({self.gaps.size_u:.2f}/{self.gaps.size_v:.2f})",
            f"  Spreads  : target={self.spreads.light_target.value}  "
            f"edge_ray={self.spreads.edge_ray.value}  "
            f"H/V=({self.spreads.global_h_deg:.1f}/{self.spreads.global_v_deg:.1f})°  "
            f"uniform_I={self.spreads.uniform_intensity}",
            f"  Solve    : {self.solve.value}  mesh={self.mesh_u}×{self.mesh_v}",
            f"  Material : R={self.reflection_coefficient:.3f}",
            f"  Facets   : {len(self.facets)} generated",
        ]
        return "\n".join(lines)



